name: CI
on: push
jobs:
  #build-test:
    #runs-on: ubuntu-latest
    #steps:
      #- run: docker build --target test --tag my-test-image .
      #- run: docker run my-test-image

  prod-check:
    #if: ${{ github.ref == 'refs/heads/main' }}
    if: ${{ github.ref == 'refs/heads/exercise-9' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"

  build-push:
    runs-on: ubuntu-latest
    needs: prod-check
    
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: leonmilcap/m9repo:latest
          labels: production

      - run: docker build --target production --tag leonmilcap/m9repo:latest . #--cache-from (?)
      - run: docker push leonmilcap/m9repo:latest
      - env: 
          WEBHOOK: ${{ secrets.AZWA_WEBHOOK }}
        run: curl -dH --fail -X POST $WEBHOOK