name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- run: echo Hello World
    - run: docker build --target test --tag my-test-image .
    - run: docker run my-test-image