name: CI
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: docker build --target test --tag my-test-image .
      - run: docker run my-test-image

  prod-check:
    #if: ${{ github.ref == 'refs/heads/main' }}
    if: ${{ github.ref == 'refs/heads/exercise-9' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"

  job-2:
    runs-on: ubuntu-latest
    needs: prod-check
    
    steps:
      - uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - run: echo "job2 placeholder"
      - run: docker build --target production --tag leonmilcap/m9repo:latest .
      - run: docker push leonmilcap/m9repo:latest
      

